### ISSUE TITLE
#5 に @hanachin が書いたコメント「:pray:」が消された理由が知りたい

### ISSUE THREAD

**Issue by hanachin** [okinawarb/meetups#10]
コメントを消すべき理由があって消したと思うので、コメント消したことについては問題ないと思っています。

消された本人としては、突然1文字だけの絵文字コメント :pray: を見て不快に感じたのだと解釈しています。

たとえコメントを書いた本人に悪意がなくても、不快に受け取られてしまうようなコメントを書いてしまったのは僕の完全に落ち度です。
不快に感じられるコメントを書いてしまったことについては申し訳ないと思っています。すみません :bow: 

弁明させてもらうとコメントの内容「:pray:」を書いた意図としては「ありがとう」のつもりで書きました。
iPhone(iOS 7)では「ありがとう」を変換すると :pray: に相当する絵文字が変換候補に表示されることによります。

「:+1:」などと違い「:pray:」1文字だけでコメントしても意味が伝わりづらいと思うので、今後同じようなことをおこさないよう、対策として絵文字のみのコメントを避けようと考えています。

ただ、あくまで上記の解釈と対策は僕の考えによるものなので、
消した理由について共有してもらえると嬉しいです。

**Comment by kimihito** [comment]
削除した当人です。そちらの解釈と僕が削除した意図は同じものです。

**Comment by hanachin** [comment]
ありがとうございます :sparkling_heart: 納得しました。
改めて、すみませんでした :bow:
