### ISSUE TITLE
GitHub用にプラグインをいれたい

### ISSUE THREAD

**Issue by hanachin** [okinawarb/meetups#16]
#14 でもコメントしましたが絵文字が変換されてないのでプラグインを足したい
- [Emoji on GitHub Pages · GitHub Help](https://help.github.com/articles/emoji-on-github-pages)
- [Using Jekyll Plugins with GitHub Pages · GitHub Help](https://help.github.com/articles/using-jekyll-plugins-with-github-pages)

**Comment by yasulab** [comment]
あ、直接コミットしてしまったorz

**Comment by hanachin** [comment]
thanks、確認します

**Comment by hanachin** [comment]
![2014-05-13 19 28 26](https://cloud.githubusercontent.com/assets/167012/2956061/610c7dda-da89-11e3-9bee-5be0c1974486.png)
こんな感じ。スタイルは後でいじったほうがよさそう。
