### ISSUE TITLE
2014-11-02と2014-12-03での実装追いの件

### ISSUE THREAD

**Issue by takumikinjo** [okinawarb/meetups#36]
2014-11-02 と 2014-12-03 の okinawarb にて MRI なソースコードで実装を追いました。

ついては、コンテンツをアップする場所に困ったので本プロジェクトの中に置こうと思います。

**Comment by yasulab** [comment]
(僕は参加してないのでアレですが) 僕は良いと思います! :smile_cat:

**Comment by takumikinjo** [comment]
@yasulab お久しぶりでーす。プルリクしてますんで良さ気でしたらマージしてやってくださいまし。

**Comment by takumikinjo** [comment]
@yasulab あざした！本件くろうずします。

**Comment by yasulab** [comment]
承知!
