### ISSUE TITLE
Railsチュートリアル対応 and/or `tweet2idobata`の実装

### ISSUE THREAD

**Issue by yasulab** [okinawarb/meetups#4]
1. Railsチュートリアル対応:
   - https://twitter.com/keita_na/status/462569346967937025
2. `tweet2idobata`:
   - [@railstutorialjp](http://twitter.com/railstutorialjp)に@mentionが来たら、Idobata.ioに通知するスクリプトが欲しい
   - :thought_balloon: (同様な感じで `hatebu2idobata`も欲しい...)

**Comment by hanachin** [comment]
すごい広島を参考にエア参加ラベル付けました :flags: 
https://github.com/great-h/great-h.github.io/issues

**Comment by yasulab** [comment]
@hanachin Good Job! :+1:

**Comment by yasulab** [comment]
今更だけど...

 :heavy_check_mark: Done! :shipit: 
1. [Railsチュートリアル対応した!!](https://github.com/yasulab/railstutorial.jp/commit/3ced51a6fc668d21ec437994c52a11d364f509f1)
2. (`tweet2idobata`ではなく`hatebu2idobata`になっちゃったけど)公開しました :sweat_smile:
   [yasulab/hatebu2idobata](https://github.com/yasulab/hatebu2idobata)

**Comment by hanachin** [comment]
もしよかったらやった内容をmdで書いてmeetupsにpull request送ってもらえると嬉しいです!
手順のせてあるので参考にしていただければ。
http://www.okinawarb.org/meetups/
