### ISSUE TITLE
meetupsの運用について書く

### ISSUE THREAD

**Issue by hanachin** [okinawarb/meetups#7]
ごい広島で採用されている方式をOkinawa.rbでも(ゆるく)採用したいです。
http://great-h.github.io/
- やりたいことをissueにかいく
- やったことの記事を書いてPull Request送る

サイト製作中ですが、記事を書くとここに乗ります!
http://www.okinawarb.org/meetups/

**Comment by kimihito** [comment]
issueありがとうございます！

> - やったことの記事を書いてPull Request送る
> 
> サイト製作中ですが、記事を書くとここに乗ります!
> http://www.okinawarb.org/meetups/

って部分が昨日のMeetupでhttps://github.com/kinjo さんと話していた疑問の回答になってると思うのでまた次回のMeetupで詳しくお話伺えればと思います〜。
